### ISSUE TITLE
How to split the dataset to train/test set?

### ISSUE THREAD

**Issue by wangguanan** [tinajia2012/ICME2018_Occluded-Person-Reidentification_datasets#1]
Is there a pre-defined split list ? or just random split the whole dataset into train/test set?

**Comment by ZOUWENMIN** [comment]
Hello, I have the same confusion. If it is a simple random division, can it be compared with the results of other papers?

**Comment by wangguanan** [comment]
please refer here:
1. https://github.com/wangguanan/light-reid/tree/master/examples/occluded_reid
2. https://github.com/wangguanan/HOReID
